### PR TITLE
Draw grid

### PR DESCRIPTION
**Pull request by vcchang-zz**
Drew the grid as per criteria. Please review the comments within the commits for more details. Would like to receive constructive feedback on any areas that you think need improvement.

### CODE REVIEW

**Comment by tamf** [comment]
You don't need to make the methods in Window.java static.

Fields generally should never be public as you don't want other classes setting them (or accessing them if they don't need to). So you should not make those fields in SnakeGame.java public.

Look at the constructor for BoardDrawer, you are given all the things you need to draw the lines without needing to "port" fields from Snakegame.java.

**Comment by vcchang-zz** [comment]
As you suggested, I merged the two existing branches (initialize-state and draw-grid).

Please have a look at my latest commit. Thank you!

**Comment by tamf** [comment]
I don't understand why you initialized a `BoardDrawer` inside the `BoardDrawer` class. Just draw it as you did before using the same pieces of information, except don't port the fields over from `SnakeGame`

**Comment by tamf** [comment]
When someone calls `drawBoard`, they are calling it on an instance of `BoardDrawer` which means the constructor for `BoardDrawer` will have previously been called.

**Comment by tamf** [comment]
[This](http://www.homeandlearn.co.uk/java/class_constructor.html) may be useful

**Pull request merged**
