### PR TITLE
Created constants for 3 SnakeGame variables

### PR DESCRIPTION
**Pull request by vcchang-zz**
- Created the following constant fields in SnakeGame class; note: this is an edit to improve Issue # 1:
  -- STARTING_DIRECTION
  -- STARTING_X_POSITION
  -- STARTING_Y_POSITION

### CODE REVIEW

**Comment by tamf** [comment]
Make one constant for the Position rather than the X and Y constants

**Comment by vcchang-zz** [comment]
Do you mean create:
private static final Position STARTING_POSITION = new Position(1, 1);

**Comment by tamf** [comment]
Yes

**Comment by vcchang-zz** [comment]
Sorry, I accidentally committed line deletion in BoardDrawer; please ignore. Thanks!

**Comment by tamf** [comment]
Next time you can undo that change and commit it

**Pull request merged**
